### ISSUE TITLE
code format strips leading indentation in certain cases

### ISSUE THREAD

**Issue by ferringb** [bartTC/dpaste#88] opened 2017-01-21 18:48 UTC
You can see a live example of this at https://dpaste.de/tWH4 .

The text in question was thus:
```
verifying spacing.
 one space leading
  two spaces leading
no spaces leading
(I feel likse this is a dr. seuss nursery rhyme)
```

which rendered incorrectly as
```
verifying spacing.
one space leading
  two spaces leading
no spaces leading
(I feel likse this is a dr. seuss nursery rhyme)
```

**Comment by jmoujaes** [comment] 2018-03-09 19:55
I can also reproduce this behavior and create a failing test. Would be happy to work on a PR :)

**Comment by bartTC** [comment] 2018-03-12 13:01
This has been fixed in the `v3` branch. The fix was two folded:

- Django does strip incoming form content by default. I didn't know this! https://docs.djangoproject.com/en/2.0/ref/forms/fields/#django.forms.CharField.strip
- The HTML was swallowing single whitespaces, because only 2+ whitespaces were substituted with `&nbsp;`. I removed the substitution and rely on CSS `white-space: pre` now.

![](https://d.pr/i/XQ4klN.png)

**Closed by bartTC** 2018-03-12 13:01 UTC
